### ISSUE TITLE
Error help me pls

### ISSUE THREAD

**Issue by netUstad** [mike42/escpos-php#1022]
Fatal error: Uncaught Error: Class 'IntlBreakIterator' not found in C:\xampp\htdocs\print\src\Mike42\Escpos\CodePage.php:188 Stack trace: #0 C:\xampp\htdocs\print\src\Mike42\Escpos\CodePage.php(73): Mike42\Escpos\CodePage::encodingArrayFromData(Array) #1 C:\xampp\htdocs\print\src\Mike42\Escpos\CapabilityProfile.php(135): Mike42\Escpos\CodePage->__construct('TCVN-3-1', Array) #2 C:\xampp\htdocs\print\src\Mike42\Escpos\CapabilityProfile.php(294): Mike42\Escpos\CapabilityProfile->__construct('default', Array) #3 C:\xampp\htdocs\print\src\Mike42\Escpos\Printer.php(367): Mike42\Escpos\CapabilityProfile::load('default') #4 C:\xampp\htdocs\print\example\interface\windows-usb.php(13): Mike42\Escpos\Printer->__construct(Object(Mike42\Escpos\PrintConnectors\WindowsPrintConnector)) #5 {main} thrown in C:\xampp\htdocs\print\src\Mike42\Escpos\CodePage.php on line 188

**Comment by Mr2YMAN** [comment]
did u fix it ?

**Comment by moaid-kash** [comment]
composer require mike42/escpos-php
