### ISSUE TITLE
Print via USB printer under Windows

### ISSUE THREAD

**Issue by vincentckk** [mike42/escpos-php#520]
Warning: copy(\\NMU-EO03\TMT88IVUSB): failed to open stream: Permission denied in C:\inetpub\escpos-php-master\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372

Fatal error: Uncaught exception 'Exception' with message 'Failed to copy file to printer' in C:\inetpub\escpos-php-master\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php:291 Stack trace: #0 C:\inetpub\escpos-php-master\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php(173): Mike42\Escpos\PrintConnectors\WindowsPrintConnector->finalizeWin('\e@\e@\eM\x01\eM\x00\ea\x01Th...') #1 C:\inetpub\escpos-php-master\src\Mike42\Escpos\Printer.php(503): Mike42\Escpos\PrintConnectors\WindowsPrintConnector->finalize() #2 C:\inetpub\escpos-php-master\ecasual\ecasual_test.php(136): Mike42\Escpos\Printer->close() #3 {main} thrown in C:\inetpub\escpos-php-master\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 291

I saw many fixed issues related to this question, however, I tried all previous solutions (Folders permission, Printer permission, Shared printer, printer name without space, etc...) but still got the above error. 

Note:
1. I tried Copy "text" \\NMU-EO03\TMT88IVUSB and got printout...
2. For sure that I worked with Network printer perfectly...

Please advise if you have same happen before and resolved.

**Comment by mike42** [comment]
I tested the Windows code for this driver on XAMPP / Windows 7, so your setup is different enough that there isn't much I can suggest to debug.

"Permission denied" in this context plainly means that either IIS is stopping you from connecting out, or the printer sharing is stopping you from connecting in. The Windows event logs, or posts from IIS users when trying to access shared files may be realistic places to start. Since we are simply copying a temp file to a UNC path in the PHP code, I don't think there is any way to get a more specific error message.

There are a variety of things that could also throw a spanner in the works, such as Windows Firewall or an overzealous antivirus product, all worth checking.

**Comment by vincentckk** [comment]
Finally, I gave up and use network printing instead. haha...

2018-02-28 16:24 GMT+08:00 Michael Billington <notifications@github.com>:

**Comment by vincentckk** [comment]
Many thanks!

2018-03-06 10:32 GMT+08:00 Vincent Cheung <vincentckk1012@gmail.com>:
