### ISSUE TITLE
Network printer  error  Xprinter 80C

### ISSUE THREAD

**Issue by zansit** [mike42/escpos-php#990]
Hi  everyone 

im trying to print my  receipt  to  a  printer (Xprinter 80c)  on the  network from  xammp.my pc  and  the  printer  are both in the  same    network  but  im   getting the  following error.

Fatal error: Uncaught Error: Call to undefined method Mike42\Escpos\CodePage::encodingArrayFromData() in C:\xampp\htdocs\test\vendor\mike42\escpos-php\src\Mike42\Escpos\CodePage.php:73 Stack trace: #0 C:\xampp\htdocs\test\vendor\mike42\escpos-php\src\Mike42\Escpos\CapabilityProfile.php(132): Mike42\Escpos\CodePage->__construct('TCVN-3-1', Array) #1 C:\xampp\htdocs\test\vendor\mike42\escpos-php\src\Mike42\Escpos\CapabilityProfile.php(291): Mike42\Escpos\CapabilityProfile->__construct('default', Array) #2 C:\xampp\htdocs\test\vendor\mike42\escpos-php\src\Mike42\Escpos\Printer.php(367): Mike42\Escpos\CapabilityProfile::load('default') #3 C:\xampp\htdocs\test\test.php(14): Mike42\Escpos\Printer->__construct(Object(Mike42\Escpos\PrintConnectors\NetworkPrintConnector)) #4 {main} thrown in C:\xampp\htdocs\test\vendor\mike42\escpos-php\src\Mike42\Escpos\CodePage.php on line 73

**Comment by Muraveiko** [comment]
https://github.com/mike42/escpos-php/issues/824
